---
# https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html

# EXPECTED EXISTING RESOURCES:
# EC2 KeyPair for SSH connection
# aws-elasticbeanstalk-ec2-role (IAM Role)
# aws-elasticbeanstalk-service-role (IAM Role)

# NOTE: all dependencies must be present in the application package, the instances can't connect to external resources!

# EB CLI:
# $ eb init <<TIER>>-<<APPLICATION>> --platform "<<PLATFORM>>" --tags type=<<LANGUAGE>>-app --verbose --region <<REGION>> --profile <<PROFILE>>
# $ eb create <<TIER>>-<<APPLICATION>>-<<ENVIRONMENT>> --cfg "prod-internal" --verbose

# LICENSE:
# This code is released under the MIT software license, see license.txt in project root for details. No warranty of any kind is
# included, and the copyright notice must be included in redistributions.

AWSConfigurationTemplateVersion: 1.1.0.0
EnvironmentTier:
    Type: Standard
    Name: WebServer
Platform:
    # ELASTIC BEANSTALK SUBSTITUTE: region & platform
    PlatformArn: arn:aws:elasticbeanstalk:<<REGION>>::platform/<<PLATFORM>>
OptionSettings:
    aws:ec2:vpc:
        # CLOUDFORMATION OUTPUT: CustomVpcId
        VPCId: <<VPC-ID>>
        # CLOUDFORMATION OUTPUT: PrivateSubnetAllId
        Subnets: <<COMMA-SEPARATED-SUBNET-IDS>>
        # DEFAULT
        ELBScheme: internal
        # DEFAULT: never use public instance IP address
        AssociatePublicIpAddress: false
    aws:ec2:instances:
        # ELASTIC BEANSTALK SUBSTITUTE: instance type(s)
        InstanceTypes: <<COMMA-SEPARATED-INSTANCE-TYPES>>
    aws:elbv2:loadbalancer:
        # CLOUDFORMATION OUTPUT: PrivateAlbId
        SharedLoadBalancer: <<LOAD-BALANCER-ARN>>
        # CLOUDFORMATION OUTPUT: PrivateAlbSecurityGroupId
        ManagedSecurityGroup: <<ALB-MANAGED-SECURITY-GROUP>>
        # CLOUDFORMATION OUTPUT: PrivateAlbSecurityGroupId
        SecurityGroups: <<COMMA-SEPARATED-ALB-SECURITY-GROUPS>>
    # ELASTIC BEANSTALK SUBSTITUTE: capitalized application name
    aws:elbv2:listenerrule:directToApp<<CAPITALIZED-APPLICATION>>:
        # NOTE: we use the public hosted DNS name for internal routing too
        # CLOUDFORMATION OUTPUT: PublicAlbHostedDns
        HostHeaders: <<HOSTED-DNS>>
        # ELASTIC BEANSTALK SUBSTITUTE: application name
        PathPatterns: /<<APPLICATION>>/*
        # DEFAULT
        Priority: 20
        Process: default
    # NOTE: port 80 HTTP is only accessible from inside the VPC
    aws:elbv2:listener:80:
        # ELASTIC BEANSTALK SUBSTITUTE: capitalized application name
        Rules: directToApp<<CAPITALIZED-APPLICATION>>
    aws:autoscaling:asg:
        # DEFAULT: minimum instance count
        MinSize: 1
        # DEFAULT: maximum instance count
        MaxSize: 3
    aws:autoscaling:launchconfiguration:
        # CLOUDFORMATION OUTPUT: PrivateInstanceSecurityGroupId
        # OPTIONAL CLOUDFORMATION OUTPUT: CacheInstanceSecurityGroupId, RdsInstanceSecurityGroupId
        SecurityGroups: <<COMMA-SEPARATED-INSTANCE-SECURITY-GROUPS>>
        # CLOUDFORMATION OUTPUT: BastionSecurityGroupId
        SSHSourceRestriction: tcp, 22, 22, <<BASTION-SECURITY-GROUP>>
        # ELASTIC BEANSTALK SUBSTITUTE: AWS EC2 Key Pair for SSH connection
        EC2KeyName: <<EC2-KEY-PAIR>>
        # DEFAULT: AWS EB profile managed by dev-ops
        IamInstanceProfile: aws-elasticbeanstalk-ec2-role
        # DEFAULT: only allow Instance MetaData Service v2 (with token based authentication)
        DisableIMDSv1: true
    aws:elasticbeanstalk:environment:
        # DEFAULT: load balancer settings
        EnvironmentType: LoadBalanced
        LoadBalancerType: application
        LoadBalancerIsShared: true
        # DEFAULT: AWS EB profile managed by dev-ops
        ServiceRole: aws-elasticbeanstalk-service-role
    aws:elasticbeanstalk:environment:process:default:
        # DEFAULT
        HealthCheckInterval: 20 # sec
        HealthCheckTimeout: 5 # sec
        HealthyThresholdCount: 3
        UnhealthyThresholdCount: 3
        # StickinessEnabled: true
        # StickinessLBCookieDuration: 604800
    aws:elasticbeanstalk:command:
        # DEFAULT
        DeploymentPolicy: AllAtOnce
        # TODO
        # DeploymentPolicy: Immutable
    aws:elasticbeanstalk:hostmanager:
        # DEFAULT: publish logs to S3
        LogPublicationControl: true
    aws:elasticbeanstalk:managedactions:
        ManagedActionsEnabled: false
    # TODO
    #     ManagedActionsEnabled: true
    #     PreferredStartTime: TUE:03:00
    #     # default AWS EB profile managed by dev-ops
    #     ServiceRoleForManagedUpdates: aws-elasticbeanstalk-service-role
    # aws:elasticbeanstalk:managedactions:platformupdate:
    #     UpdateLevel: minor
