---
# https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html

# EXPECTED EXISTING RESOURCES:
# reloaded-eb-admin-key (EC2 KeyPair)
# aws-elasticbeanstalk-ec2-role (IAM Role)
# aws-elasticbeanstalk-service-role (IAM Role)

# NOTE: all dependencies must be present in the application package, the instances can't connect to external resources!

# EB CLI:
# $ eb init <<TIER>>-<<APPLICATION>> --platform "<<PLATFORM>>" --tags type=<<LANGUAGE>>-app --verbose --region <<REGION>> --profile <<PROFILE>>
# $ eb create <<TIER>>-<<APPLICATION>>-<<ENVIRONMENT>> --cfg "prod-public" --verbose

# LICENSE:
# This code is released under the MIT software license, see license.txt in project root for details. No warranty of any kind is
# included, and the copyright notice must be included in redistributions.

AWSConfigurationTemplateVersion: 1.1.0.0
EnvironmentTier:
    Type: Standard
    Name: WebServer
Platform:
    # ELASTIC BEANSTALK SUBSTITUTE: region & platform
    PlatformArn: arn:aws:elasticbeanstalk:<<REGION>>::platform/<<PLATFORM>>
OptionSettings:
    aws:ec2:vpc:
        # CLOUDFORMATION OUTPUT: CustomVpcId
        VPCId: <<VPC-ID>>
        # NOTE: private subnets, even if public facing setup
        # CLOUDFORMATION OUTPUT: PrivateSubnetAllId
        Subnets: <<COMMA-SEPARATED-SUBNET-IDS>>
        # DEFAULT: "public" (for public facing applications)
        ELBScheme: public
        # DEFAULT: never use public instance IP address
        AssociatePublicIpAddress: false
    aws:ec2:instances:
        # ELASTIC BEANSTALK SUBSTITUTE: instance type(s)
        InstanceTypes: <<COMMA-SEPARATED-INSTANCE-TYPES>>
    aws:elbv2:loadbalancer:
        # CLOUDFORMATION OUTPUT: PublicAlbId (for public facing applications)
        SharedLoadBalancer: <<LOAD-BALANCER-ARN>>
        # CLOUDFORMATION OUTPUT: PublicAlbSecurityGroupId (for public facing applications)
        ManagedSecurityGroup: <<ALB-MANAGED-SECURITY-GROUP>>
        # CLOUDFORMATION OUTPUT: PublicAlbSecurityGroupId (for public facing applications)
        SecurityGroups: <<COMMA-SEPARATED-ALB-SECURITY-GROUPS>>
    # ELASTIC BEANSTALK SUBSTITUTE: capitalized application name
    aws:elbv2:listenerrule:directToApp<<CAPITALIZED-APPLICATION>>:
        # CLOUDFORMATION OUTPUT: PublicAlbHostedDns (for public facing applications)
        HostHeaders: <<HOSTED-DNS>>
        # ELASTIC BEANSTALK SUBSTITUTE: application name
        PathPatterns: /<<APPLICATION>>/*
        # DEFAULT
        Priority: 20
        Process: default
    # NOTE: port 80 HTTP is only accessible from inside the VPC (for public facing applications)
    aws:elbv2:listener:80:
        # ELASTIC BEANSTALK SUBSTITUTE: capitalized application name
        Rules: directToApp<<CAPITALIZED-APPLICATION>>
    # NOTE: enable port 443 HTTPS (for public facing applications)
    aws:elbv2:listener:443:
        # ELASTIC BEANSTALK SUBSTITUTE: capitalized application name
        Rules: directToApp<<CAPITALIZED-APPLICATION>>
    aws:autoscaling:asg:
        # DEFAULT: minimum instance count
        MinSize: 1
        # DEFAULT: maximum instance count
        MaxSize: 3
    aws:autoscaling:launchconfiguration:
        # NOTE: instance security is private, even if public facing setup
        # CLOUDFORMATION OUTPUT: PrivateInstanceSecurityGroupId
        SecurityGroups: <<INSTANCE-SECURITY-GROUP>>
        # CLOUDFORMATION OUTPUT: BastionSecurityGroupId
        SSHSourceRestriction: tcp, 22, 22, <<BASTION-SECURITY-GROUP>>
        # DEFAULT: AWS EC2 Key Pair managed by dev-ops
        EC2KeyName: reloaded-eb-admin-key
        # DEFAULT: AWS EB profile managed by dev-ops
        IamInstanceProfile: aws-elasticbeanstalk-ec2-role
        # DEFAULT: only allow Instance MetaData Service v2 (token based authentication)
        DisableIMDSv1: true
    aws:elasticbeanstalk:environment:
        # DEFAULT: load balancer settings
        EnvironmentType: LoadBalanced
        LoadBalancerType: application
        LoadBalancerIsShared: true
        # DEFAULT: AWS EB profile managed by dev-ops
        ServiceRole: aws-elasticbeanstalk-service-role
    aws:elasticbeanstalk:environment:process:default:
        # DEFAULT
        HealthCheckInterval: 20 # sec
        HealthyThresholdCount: 3
        UnhealthyThresholdCount: 3
    aws:elasticbeanstalk:command:
        # DEFAULT
        DeploymentPolicy: AllAtOnce
        # TODO
        # DeploymentPolicy: Immutable
    aws:elasticbeanstalk:hostmanager:
        # DEFAULT: publish logs to S3
        LogPublicationControl: true
    aws:elasticbeanstalk:managedactions:
        ManagedActionsEnabled: false
        # TODO
        # ManagedActionsEnabled: true
        # PreferredStartTime: TUE:03:00
        # # default AWS EB profile managed by dev-ops
        # ServiceRoleForManagedUpdates: aws-elasticbeanstalk-service-role
    # aws:elasticbeanstalk:managedactions:platformupdate:
    #     UpdateLevel: minor
